// Command reset scans all packages below the working directory, finds structs
// annotated with // generate:reset, and writes a Reset() method for each one
// to reset.gen.go in that package's directory.
//
// Usage:
//
//	go run ./cmd/reset
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const marker = "generate:reset"

var primitiveZero = map[string]string{
	"bool":       "false",
	"string":     `""`,
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uintptr":    "0",
	"byte":       "0",
	"rune":       "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || !d.IsDir() {
			return err
		}

		return processDir(path)
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		n := fi.Name()
		return !strings.HasSuffix(n, "_test.go") && n != "reset.gen.go"
	}, parser.ParseComments)
	if err != nil {
		return nil
	}

	for pkgName, pkg := range pkgs {
		var methods []string
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				marked := hasMarker(gd.Doc)
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					if !marked && !hasMarker(ts.Doc) {
						continue
					}
					methods = append(methods, buildMethod(ts.Name.Name, st))
				}
			}
		}
		if len(methods) == 0 {
			continue
		}
		if err := writeGenFile(dir, pkgName, methods); err != nil {
			return err
		}
		fmt.Printf("generated: %s/reset.gen.go\n", filepath.ToSlash(dir))
	}
	return nil
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Contains(c.Text, marker) {
			return true
		}
	}
	return false
}

func buildMethod(typeName string, st *ast.StructType) string {
	recv := strings.ToLower(typeName[:1])
	var b strings.Builder
	fmt.Fprintf(&b, "func (%s *%s) Reset() {\n", recv, typeName)
	fmt.Fprintf(&b, "if %s == nil { return }\n", recv)
	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			resetField(&b, recv+"."+name.Name, field.Type)
		}
	}
	fmt.Fprintln(&b, "}")
	return b.String()
}

func resetField(b *strings.Builder, ref string, typ ast.Expr) {
	switch t := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero[t.Name]; ok {
			fmt.Fprintf(b, "%s = %s\n", ref, zero)
		} else {
			fmt.Fprintf(b, "if r, ok := any(&%s).(interface{ Reset() }); ok { r.Reset() }\n", ref)
		}
	case *ast.StarExpr:
		fmt.Fprintf(b, "if %s != nil {\n", ref)
		if id, ok := t.X.(*ast.Ident); ok {
			if zero, ok := primitiveZero[id.Name]; ok {
				fmt.Fprintf(b, "*%s = %s\n", ref, zero)
				fmt.Fprintln(b, "}")
				return
			}
		}
		// Pointer to struct or external type — call Reset() if it exists.
		fmt.Fprintf(b, "if r, ok := any(%s).(interface{ Reset() }); ok { r.Reset() }\n", ref)
		fmt.Fprintln(b, "}")
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(b, "%s = %s[:0]\n", ref, ref)
		}
	case *ast.MapType:
		fmt.Fprintf(b, "clear(%s)\n", ref)
	}
}

func writeGenFile(dir, pkgName string, methods []string) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by reset generator. DO NOT EDIT.\n\npackage %s\n\n", pkgName)
	for _, m := range methods {
		fmt.Fprintln(&b, m)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format %s/reset.gen.go: %w", dir, err)
	}
	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
}
