// Code generated by reset generator. DO NOT EDIT.

package service

func (b *BatchItem) Reset() {
	if b == nil {
		return
	}
	b.ShortID = ""
	b.OriginalURL = ""
}

func (u *UserURL) Reset() {
	if u == nil {
		return
	}
	u.ShortURL = ""
	u.OriginalURL = ""
}

func (d *DeleteTask) Reset() {
	if d == nil {
		return
	}
	d.ShortID = ""
	d.UserID = ""
}
